### ISSUE TITLE
I have MY13_MY14_RA4_15_26_1.zip

### ISSUE THREAD

**Issue by jeffallen** [jason0x90/uconnect-swdl#1]
If you're interested... :)

**Comment by jason0x90** [comment]
Hey, I'm not really sure if that would be helpful or not, unless you know something I don't!  This version had something very interesting in it which looked like a backdoor that you could use to upload custom firmware as I've put in the wiki:

https://github.com/jasonswan/uconnect-swdl/wiki/Almost-there...

**Comment by jeffallen** [comment]
The ISO signature checking has been moved to ioschk.lua. It is called from
RA4/usr/share/scripts/install.sh.

Do you know where install.sh is called from? It really seems like it would
be possible to put a null isochk.lua on the ISO, because even though it
seems ridiculous, it seems like they are using the unverified isochk.lua in
order to check the ISO?!?!?

**Comment by jeffallen** [comment]
Also: the "if S in byte 128" nonsense is gone. Now to skip the check, the
hardware needs to report a certain value via the /dev/fram/mfg file.
Decompiled lua:

get_flags = function()
  -- function num : 0_0
  local l_1_0 = (io.open)("/dev/fram/mfg", "r")
  if l_1_0 then
    local l_1_1 = l_1_0:seek("set", 0)
    do
      do
        if l_1_1 and l_1_1 == 0 then
          local l_1_2 = l_1_0:read(2)
          if l_1_2 and l_1_2 ~= 0 then
            l_1_0:close()
            return l_1_2
          end
        end
        l_1_0:close()
        return nil
      end
    end
  end
end

if get_flags() == "MS" then
  print("Mfg install mode")
  ;
  (os.exit)(0)
else
  print("Normal install mode")
end
... check sig here ...

**Comment by eenti** [comment]
Hey, I hope it's okay for me to write here, I'm a bit new to Github and I apologize if I'm bothering you.

I have a 2014 Jeep Cherokee and they recommended updating it, however it gives me the error "Sierra Wireless: bolo file install failed" in step 11 of 14 (Embedded Air Card).

I am in the Dominican Republic and here, apart from being more expensive, it has been much more difficult for me to find help for this.

I know it's been a while but if you remember something I can search the archives and help me bypass that Sierra Wireless (assuming that's a chipset) or with anything else to be able to use the radio again.

Everything was working correctly before installation (apart from the built-in phone in the vehicle that I never used so I don't know if it's all right).

All I need is to listen to music on the go and the extended AC control.

**Comment by jeffallen** [comment]
Sorry, I stopped working on this in 2015, no clue.
